apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: remove-temp
      image: alpine:3.19
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/source/tmp || true
        echo "Cleanup done."

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose-tests
spec:
  steps:
    - name: run-nose
      image: python:3.11-slim
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        pip install --no-cache-dir nose
        nosetests -v
